Hello Microverse Project Pull Request
tobuya/Hello-Microverse pull request #1
Opened 2022-10-25 20:30 UTC by tobuya

2022-10-25 21:03 UTC, anagudelogu requested changes
Hi @tobuya, I'm Andres, your code reviewer.

Great job documenting your code professionally! 🍾 🎆 
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/l2Je9zHYveK012EVi/giphy.gif"/>

## Highlights
✅ Great PR summary and title. 🥇 
✅ Descriptive README file. 🗒️ 
✅ Descriptive commit messages. 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 21:03 UTC, anagudelogu commented on test.md
> +This file should be ignored by git
- [ ] I noticed that you included this file in your `.gitignore` file in your `main` branch after creating the `htmlcss-linters` one. The problem is that this last branch doesn't know about that change, and it doesn't have a `.gitignore` file. You're almost there! 💯. Please fix this, as stated in the requirements, this file should be ignored by git. 🛠️ 

Requirements:
![image](https://user-images.githubusercontent.com/77069011/197880886-ced9221f-72cf-496e-91ae-c0fef96534df.png)

Your actual Git graph:
![image](https://user-images.githubusercontent.com/77069011/197880680-9702c208-6027-484d-a1dc-c48b70c55b21.png)

2022-10-26 05:48 UTC, tobuya commented
Thanks for the feedback.
It's done.

On Wed, Oct 26, 2022 at 12:04 AM Andres Agudelo Guzman <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @tobuya <https://github.com/tobuya>, I'm Andres, your code reviewer.
>
> Great job documenting your code professionally! 🍾 🎆
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
>
> <https://camo.githubusercontent.com/f3ef08d74004d131ec8b159edf646c48ea914c797f3777b8da551bb5a0cddfea/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f6c324a65397a485976654b3031324556692f67697068792e676966>
> Highlights
>
> ✅ Great PR summary and title. 🥇
> ✅ Descriptive README file. 🗒️
> ✅ Descriptive commit messages. 💯
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In test.md
> <https://github.com/tobuya/Hello-Microverse/pull/1#discussion_r1004960390>
> :
>
> > @@ -0,0 +1 @@
>
> +This file should be ignored by git
>
>
>
>    - I noticed that you included this file in your .gitignore file in
>    your main branch after creating the htmlcss-linters one. The problem
>    is that this last branch doesn't know about that change, and it doesn't
>    have a .gitignore file. You're almost there! 💯. Please fix this, as
>    stated in the requirements, this file should be ignored by git. 🛠️
>
> Requirements:
> [image: image]
> <https://user-images.githubusercontent.com/77069011/197880886-ced9221f-72cf-496e-91ae-c0fef96534df.png>
>
> Your actual Git graph:
> [image: image]
> <https://user-images.githubusercontent.com/77069011/197880680-9702c208-6027-484d-a1dc-c48b70c55b21.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tobuya/Hello-Microverse/pull/1#pullrequestreview-1155492043>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUVRSDG56NXMCD76GBE2K4DWFBDMHANCNFSM6AAAAAAROKPFX4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-26 06:13 UTC, jerryowusu requested changes
Hi @tobuya 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close](https://user-images.githubusercontent.com/65233860/197948499-d80d475b-6909-4e37-9298-ee2a1fb51910.gif)


 ## Highlights
:heavy_check_mark: All linters are passing
:heavy_check_mark: Excellent descriptive PR and summary

 ## Required Changes ♻️

- [ ] As the previous reviewer indicated, your project should have the `.gitignore` and `test.md` file. However, you need to add the `test.md` file to the `.gitignore` file which will prevent the `test.md` file from being pushed into the github repository.

_Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] The `node_modules` directory should also be added to the `.gitignore` file
- [ ] [OPTIONAL]  You currently do not have a valid readme file. Kindly consider using [the proffessional](https://github.com/microverseinc/readme-template/blob/master/README.md) template provided by microverse and edit all sections according to your credentials and project.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 11:25 UTC, tobuya commented
> Hi @tobuya
> 
> Great work on making the changes requested by a previous reviewer 👏 You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
> 
> ![so-close](https://user-images.githubusercontent.com/65233860/197948499-d80d475b-6909-4e37-9298-ee2a1fb51910.gif) [ ![so-close](https://user-images.githubusercontent.com/65233860/197948499-d80d475b-6909-4e37-9298-ee2a1fb51910.gif) ](https://user-images.githubusercontent.com/65233860/197948499-d80d475b-6909-4e37-9298-ee2a1fb51910.gif) [ ](https://user-images.githubusercontent.com/65233860/197948499-d80d475b-6909-4e37-9298-ee2a1fb51910.gif)
> 
> ## Highlights
> ✔️ All linters are passing ✔️ Excellent descriptive PR and summary
> 
> ## Required Changes ♻️
> * [ ]  As the previous reviewer indicated, your project should have the `.gitignore` and `test.md` file. However, you need to add the `test.md` file to the `.gitignore` file which will prevent the `test.md` file from being pushed into the github repository.
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> * [ ]  [OPTIONAL] The `node_modules` directory should also be added to the `.gitignore` file
> * [ ]  [OPTIONAL]  You currently do not have a valid readme file. Kindly consider using [the proffessional](https://github.com/microverseinc/readme-template/blob/master/README.md) template provided by microverse and edit all sections according to your credentials and project.
> 
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@jerryowusu Thank you for the reply. Does this mean I commit the `test.md` file in my main branch? I am a little confused because I already have `test.md` file added on the `.gitignore` file.  Thanks for the assistance, I really appreciate it.

2022-10-26 13:22 UTC, tobuya commented on test.md
> +This file should be ignored by git
@anagudelogu Thanks for the feedback. Please can you check it now and guide me on it? I have a single review request pending and I would like the project to be approved so that I can move onto the next one. Thank you in advance.

2022-10-26 18:44 UTC, closed without merging